### Banking Questions

In [1]:
import numpy as np
import pandas as pd
# Banking data: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [101, 5000, 720, 45, 3],
    [102, 12000, 680, 52, 5],
    [103, 2500, 610, 12, 1],
    [104, 7800, 790, 67, 4],
    [105, 3000, 550, 8, 2],
    [106, 16000, 845, 89, 6],
    [107, 4000, 700, 35, 2],
    [108, 980, 600, 22, 1],
    [109, 22000, 890, 103, 8],
    [110, 500, 430, 5, 3]
])

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")



ORIGINAL BANKING DATA:
[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]

Data shape: (10, 5)
Data type: int64


In [ ]:
### Question 1: Array Creation and Manipulation


**Q1.1:** Create a 4x4 identity matrix using `np.eye()`


In [12]:
IM = np.eye(4)
print(IM)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
**Q1.2:** Create an array of 8 zeros using `np.zeros()`


In [13]:
zeros = np.zeros(8)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
**Q1.3:** Create an array of 6 ones using `np.ones()`


In [14]:
array = np.ones(6)
array

array([1., 1., 1., 1., 1., 1.])

In [ ]:
**Q1.4:** Create an array with values from 0 to 15 using `np.arange()`


In [16]:
array = np.arange(0,16)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
**Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`


In [17]:
evenly_space = np.linspace(0,100,8)
print(evenly_space)

[  0.    14.29  28.57  42.86  57.14  71.43  85.71 100.  ]


In [ ]:
### Question 2: Array Attributes and Information

**Q2.1:** What is the shape of the `banking_data` array?


In [18]:
print(f"shape:{banking_data.shape}")

shape:(10, 5)


In [ ]:
**Q2.2:** What is the data type of the `banking_data` array?


In [19]:
print(f"Data type: {banking_data.dtype}")


Data type: int64


In [ ]:
**Q2.3:** What is the size (total number of elements) of the `banking_data` array?


In [20]:
print(f"Size: {banking_data.size}")


Size: 50


In [ ]:
**Q2.4:** What is the number of dimensions of the `banking_data` array?


In [21]:
print(f"dimension:{banking_data.ndim}")

dimension:2


In [ ]:
**Q2.5:** What is the memory size of the `banking_data` array in bytes?


In [4]:
print(f"size:{banking_data.nbytes}")

size:400


In [ ]:
### Question 3: Indexing and Slicing

**Q3.1:** Extract the first row of `banking_data`


In [5]:
first_row = banking_data[0]
print(first_row)

[ 101 5000  720   45    3]


In [ ]:
**Q3.2:** Extract the last row of `banking_data`


In [7]:
last_row = banking_data[-1]
print(last_row)

[110 500 430   5   3]


In [ ]:
**Q3.3:** Extract the Account_Balance column (column index 1)


In [8]:
Account_Balance = banking_data[:,1]
print(Account_Balance)

[ 5000 12000  2500  7800  3000 16000  4000   980 22000   500]


In [ ]:
**Q3.4:** Extract the first 4 rows and first 3 columns


In [9]:
bank = banking_data[:4,:3]
print(bank)

[[  101  5000   720]
 [  102 12000   680]
 [  103  2500   610]
 [  104  7800   790]]


In [ ]:
**Q3.5:** Extract rows 3 to 7 (inclusive)


In [10]:
bank = banking_data[2:7]
print(bank)

[[  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]]


In [2]:
import numpy as np
import pandas as pd
# Banking data: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [101, 5000, 720, 45, 3],
    [102, 12000, 680, 52, 5],
    [103, 2500, 610, 12, 1],
    [104, 7800, 790, 67, 4],
    [105, 3000, 550, 8, 2],
    [106, 16000, 845, 89, 6],
    [107, 4000, 700, 35, 2],
    [108, 980, 600, 22, 1],
    [109, 22000, 890, 103, 8],
    [110, 500, 430, 5, 3]
])

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")



ORIGINAL BANKING DATA:
[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]

Data shape: (10, 5)
Data type: int64


In [ ]:
### Question 4: Mathematical Operations

**Q4.1:** Calculate the sum of all account balances


In [4]:
Total_price = np.sum(banking_data[:,1])
print(f"Total price:${Total_price}")

Total price:$73780


In [ ]:
**Q4.2:** Calculate the mean account balance


In [5]:
mean = np.mean(banking_data[:,1])
print(f"mean price:${mean}")

mean price:$7378.0


In [ ]:
**Q4.3:** Calculate the standard deviation of account balances


In [7]:
SD = np.std(banking_data[:,1])
print(f"std dv:${SD:.2f}")

std dv:$6767.21


In [ ]:
**Q4.4:** Calculate the variance of account balances


In [9]:
variance = np.var(banking_data[:,1])
print(f"Var:${variance:.2f}")

Var:$45795156.00


In [ ]:
**Q4.5:** Calculate the median account balance


In [10]:
Median = np.median(banking_data[:,1])
print(f"Med:${Median:.2f}")

Med:$4500.00


In [ ]:
### Question 5: Statistical Functions

**Q5.1:** Find the minimum and maximum account balances


In [11]:
min_price = np.min(banking_data[:,1])
max_price = np.max(banking_data[:,1])
print(f"Min:${min_price}")
print(f"Max:${max_price}")

Min:$500
Max:$22000


In [ ]:
**Q5.2:** Find the minimum and maximum credit scores


In [12]:
min_credit = np.min(banking_data[:,2])
max_credit = np.max(banking_data[:,2])
print(f"Min:${min_credit}")
print(f"Max:${max_credit}")

Min:$430
Max:$890


In [ ]:
**Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)


In [13]:
Percentile = np.percentile(banking_data[:,1],[25,50,75])
print(f"25th:{Percentile[0]}")
print(f"50th:{Percentile[1]}")
print(f"75th:{Percentile[2]}")

25th:2625.0
50th:4500.0
75th:10950.0


In [ ]:
**Q5.4:** Calculate the correlation between account balance and credit score


In [14]:
correlation = np.corrcoef(banking_data[:,1],banking_data[:,2])[0,1]
print(f"Correlation:{correlation:.4f}")

Correlation:0.8373


In [ ]:
**Q5.5:** Calculate the covariance between account balance and credit score


In [15]:
covariance = np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print(f"Covariance:{covariance:.4f}")

Covariance:835436.6667


In [ ]:
### Question 6: Array Reshaping and Manipulation

**Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns


In [17]:
Reshape = banking_data.reshape(5,10)
print(Reshape)

[[  101  5000   720    45     3   102 12000   680    52     5]
 [  103  2500   610    12     1   104  7800   790    67     4]
 [  105  3000   550     8     2   106 16000   845    89     6]
 [  107  4000   700    35     2   108   980   600    22     1]
 [  109 22000   890   103     8   110   500   430     5     3]]


In [ ]:
**Q6.2:** Flatten the `banking_data` to a 1D array


In [18]:
Flatten = banking_data.flatten()
print(Flatten)

[  101  5000   720    45     3   102 12000   680    52     5   103  2500
   610    12     1   104  7800   790    67     4   105  3000   550     8
     2   106 16000   845    89     6   107  4000   700    35     2   108
   980   600    22     1   109 22000   890   103     8   110   500   430
     5     3]


In [ ]:
**Q6.3:** Transpose the `banking_data`


In [20]:
Transposed = banking_data.T
print(Transposed)

[[  101   102   103   104   105   106   107   108   109   110]
 [ 5000 12000  2500  7800  3000 16000  4000   980 22000   500]
 [  720   680   610   790   550   845   700   600   890   430]
 [   45    52    12    67     8    89    35    22   103     5]
 [    3     5     1     4     2     6     2     1     8     3]]


In [ ]:
**Q6.4:** Split the `banking_data` into 2 equal parts vertically


In [21]:
Ver_split = np.vsplit(banking_data,2)
print("first part:")
print(Ver_split[0])
print("\nsecond part:")
print(Ver_split[1])

first part:
[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]]

second part:
[[  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]


In [ ]:
**Q6.5:** Split the `banking_data` into 2 equal parts horizontally


In [25]:
Hor_split = np.hsplit(banking_data,2)
print("first part:")
print(Hor_split[0])
print("\nsecond part:")
print(Hor_split[1])

ValueError: array split does not result in an equal division

In [27]:
import numpy as np
import pandas as pd
# Banking data: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [101, 5000, 720, 45, 3],
    [102, 12000, 680, 52, 5],
    [103, 2500, 610, 12, 1],
    [104, 7800, 790, 67, 4],
    [105, 3000, 550, 8, 2],
    [106, 16000, 845, 89, 6],
    [107, 4000, 700, 35, 2],
    [108, 980, 600, 22, 1],
    [109, 22000, 890, 103, 8],
    [110, 500, 430, 5, 3]
])

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")



ORIGINAL BANKING DATA:
[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]

Data shape: (10, 5)
Data type: int64


In [ ]:
### Question 7: Logical Operations and Filtering

**Q7.1:** Find customers with account balance greater than $6000


In [31]:
Acc_balance = banking_data[banking_data[:,1]> 6000]
print(Acc_balance)

[[  102 12000   680    52     5]
 [  104  7800   790    67     4]
 [  106 16000   845    89     6]
 [  109 22000   890   103     8]]


In [ ]:
**Q7.2:** Find customers with credit score greater than 800


In [32]:
cerdit_score = banking_data[banking_data[:,2]>800]
print(cerdit_score)

[[  106 16000   845    89     6]
 [  109 22000   890   103     8]]


In [ ]:
**Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750


In [34]:
x = banking_data[(banking_data[:,3]>50) & (banking_data[:,2]<750)]
print(x)

[[  102 12000   680    52     5]]


In [ ]:
**Q7.4:** Count how many customers have account balance between $5000 and $10000


In [42]:
acc_balance_count =  np.sum((banking_data[:,1]>=5000) & (banking_data[:,1]<=10000))
print(f"balance in range 5k and 10k:{acc_balance_count} ")

balance in range 5k and 10k:2 


In [ ]:
**Q7.5:** Find the index of the customer with the highest credit score


In [44]:
high_credit = np.argmax(banking_data[:,2])
print(f"Index:{high_credit},Customer ID:{banking_data[high_credit,0]}")

Index:8,Customer ID:109


In [ ]:
### Question 8: Sorting and Searching

**Q8.1:** Sort the `banking_data` by account balance (ascending)


In [47]:
Ascending_balance = banking_data[banking_data[:,1].argsort()]
print(Ascending_balance)

[[  110   500   430     5     3]
 [  108   980   600    22     1]
 [  103  2500   610    12     1]
 [  105  3000   550     8     2]
 [  107  4000   700    35     2]
 [  101  5000   720    45     3]
 [  104  7800   790    67     4]
 [  102 12000   680    52     5]
 [  106 16000   845    89     6]
 [  109 22000   890   103     8]]


In [ ]:
**Q8.2:** Sort the `banking_data` by credit score (descending)


In [52]:
descending_credit = banking_data[(-banking_data[:,2]).argsort()]
print(descending_credit)

[[  109 22000   890   103     8]
 [  106 16000   845    89     6]
 [  104  7800   790    67     4]
 [  101  5000   720    45     3]
 [  107  4000   700    35     2]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  108   980   600    22     1]
 [  105  3000   550     8     2]
 [  110   500   430     5     3]]


In [ ]:
**Q8.3:** Find the indices that would sort the array by years active


In [53]:
years_active = np.argsort(banking_data[:,4])
print(years_active)

[2 7 4 6 0 9 3 1 5 8]


In [ ]:
**Q8.4:** Find the customer with the second highest account balance


In [56]:
second_highest_idx = np.argsort(banking_data[:,1])[-2]
second_highest_customer = banking_data[second_highest_idx]
print(f"customer ID:{second_highest_customer[0]},Balace:${second_highest_customer[1]}")


customer ID:106,Balace:$16000


In [ ]:
**Q8.5:** Find the customer with the lowest transaction count


In [62]:
x = np.argmin(banking_data[:,3])
print(f"IDX:{x},Customer ID:{banking_data[x]}")

IDX:9,Customer ID:[110 500 430   5   3]


In [ ]:
### Question 9: Mathematical Functions

**Q9.1:** Calculate the absolute values of all elements


In [63]:
absolute_values = np.abs(banking_data)
print(absolute_values)

[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]


In [ ]:
**Q9.2:** Calculate the square root of all account balances


In [64]:
sqr_rt = np.sqrt(banking_data[:,1])
print(sqr_rt)

[ 70.71067812 109.5445115   50.          88.31760866  54.77225575
 126.49110641  63.2455532   31.30495168 148.32396974  22.36067977]


In [ ]:
**Q9.3:** Calculate the square of all credit scores


In [65]:
square = np.square(banking_data[:,2])
print(square)

[518400 462400 372100 624100 302500 714025 490000 360000 792100 184900]


In [ ]:
**Q9.4:** Calculate the exponential of all transaction counts


In [66]:
exponential = np.exp(banking_data[:,3])
print(exponential)

[3.49342711e+19 3.83100800e+22 1.62754791e+05 1.25236317e+29
 2.98095799e+03 4.48961282e+38 1.58601345e+15 3.58491285e+09
 5.39922761e+44 1.48413159e+02]


In [ ]:
**Q9.5:** Calculate the natural logarithm of all account balances


In [67]:
logarithm = np.log(banking_data[:,1])
print(logarithm)

[8.51719319 9.39266193 7.82404601 8.96187901 8.00636757 9.680344
 8.29404964 6.88755257 9.99879773 6.2146081 ]


In [ ]:
### Question 10: Advanced Operations

**Q10.1:** Calculate the cumulative sum of account balances


In [68]:
cumulative_sum = np.cumsum(banking_data[:,1])
print(cumulative_sum)

[ 5000 17000 19500 27300 30300 46300 50300 51280 73280 73780]


In [ ]:
**Q10.2:** Calculate the cumulative product of transaction counts


In [69]:
cumulative_product = np.cumprod(banking_data[:,3])
print(cumulative_product)

[             45            2340           28080         1881360
        15050880      1339528320     46883491200   1031436806400
 106237991059200 531189955296000]


In [ ]:
**Q10.3:** Calculate the difference between consecutive account balances


In [70]:
difference = np.diff(banking_data[:,1])
print(difference)

[  7000  -9500   5300  -4800  13000 -12000  -3020  21020 -21500]


In [ ]:
**Q10.4:** Calculate the gradient of account balances


In [71]:
gradient = np.gradient(banking_data[:,1])
print(gradient)

[  7000.  -1250.  -2100.    250.   4100.    500.  -7510.   9000.   -240.
 -21500.]


In [ ]:
**Q10.5:** Calculate the histogram of account balances with 5 bins


In [72]:
hist_balance,bins_edges = np.histogram(banking_data[:,1],bins=5)
print(f"Histogram counts:{hist_balance}")
print(f"Bins Edges:{bins_edges}")

Histogram counts:[5 2 1 1 1]
Bins Edges:[  500.  4800.  9100. 13400. 17700. 22000.]


In [ ]:
### Question 11: Random Numbers and Simulation

**Q11.1:** Generate 6 random integers between 1 and 1000


In [73]:
Random_integers = np.random.randint(1,101,6)
print(Random_integers)

[81 73 50 56 72 15]


In [ ]:
**Q11.2:** Generate 6 random floats between 0 and 1


In [75]:
floats = np.random.random(6)
print(floats)

[0.25004824 0.32080875 0.47446522 0.66300533 0.20716957 0.42069139]


In [ ]:
**Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)


In [76]:
Random_numbers = np.random.normal(700,100,6)
print(Random_numbers)

[699.05327688 760.33774878 746.47227581 544.91771211 779.5689433
 918.42200358]


In [ ]:
**Q11.4:** Shuffle the `banking_data` rows randomly


In [77]:
Shuffled_data = banking_data.copy()
np.random.shuffle(Shuffled_data)
print(Shuffled_data)

[[  101  5000   720    45     3]
 [  107  4000   700    35     2]
 [  102 12000   680    52     5]
 [  106 16000   845    89     6]
 [  105  3000   550     8     2]
 [  104  7800   790    67     4]
 [  110   500   430     5     3]
 [  103  2500   610    12     1]
 [  109 22000   890   103     8]
 [  108   980   600    22     1]]


In [ ]:
**Q11.5:** Set random seed to 123 and generate 4 random numbers


In [79]:
np.random.seed(123)
Random_seed = np.random.random(4)
print(Random_seed)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [ ]:
### Question 12: Linear Algebra Operations

**Q12.1:** Calculate the dot product of account balance and credit score columns


In [80]:
dot_product = np.dot(banking_data[:,1],banking_data[:,2])
print(f"Dot Product:{dot_product}")

Dot Product:57800000


In [ ]:
**Q12.2:** Calculate the cross product of first two rows


In [84]:
cross_product = np.cross(banking_data[0,:3],banking_data[1,:3])
print(cross_product)

[-740000  -14110  360000]


In [ ]:
**Q12.3:** Calculate the norm (magnitude) of the account balance column


In [86]:
Norm = np.linalg.norm(banking_data[:,1])
print(f"Norm:{Norm:.2f}")

Norm:31659.13


In [ ]:
**Q12.4:** Create a 3x3 matrix and calculate its determinant


In [90]:
matrix_3x3 = np.array([[4,2,3],[9,5,6],[8,7,9]])
determinant = np.linalg.det(matrix_3x3)
print(f"Matrix:\n{matrix_3x3}")
print(f"Determinant:{determinant}")

Matrix:
[[4 2 3]
 [9 5 6]
 [8 7 9]]
Determinant:15.000000000000007


In [ ]:
**Q12.5:** Calculate the inverse of the 3x3 matrix


In [93]:
Inverse_matrix = np.linalg.inv(matrix_3x3)
print(f"Inverse:{Inverse_matrix}")

Inverse:[[ 0.2         0.2        -0.2       ]
 [-2.2         0.8         0.2       ]
 [ 1.53333333 -0.8         0.13333333]]


In [95]:
import numpy as np
import pandas as pd
# Banking data: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [101, 5000, 720, 45, 3],
    [102, 12000, 680, 52, 5],
    [103, 2500, 610, 12, 1],
    [104, 7800, 790, 67, 4],
    [105, 3000, 550, 8, 2],
    [106, 16000, 845, 89, 6],
    [107, 4000, 700, 35, 2],
    [108, 980, 600, 22, 1],
    [109, 22000, 890, 103, 8],
    [110, 500, 430, 5, 3]
])

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")



ORIGINAL BANKING DATA:
[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]

Data shape: (10, 5)
Data type: int64


In [ ]:
### Question 13: String Operations

**Q13.1:** Convert all customer IDs to strings


In [96]:
Customer_id_str = banking_data[:,0].astype(str)
print(Customer_id_str)

['101' '102' '103' '104' '105' '106' '107' '108' '109' '110']


In [ ]:
**Q13.2:** Check if any customer ID contains '100'


In [99]:
customer_100 = np.char.find(Customer_id_str,'100')>=0
print(customer_100)


[False False False False False False False False False False]


In [ ]:
**Q13.3:** Convert all customer IDs to uppercase (if they were strings)


In [100]:
Uppercase = np.char.upper(Customer_id_str)
print(Uppercase)

['101' '102' '103' '104' '105' '106' '107' '108' '109' '110']


In [ ]:
**Q13.4:** Count the length of each customer ID string


In [102]:
count = np.char.str_len(Customer_id_str)
print(count)

[3 3 3 3 3 3 3 3 3 3]


In [ ]:
**Q13.5:** Replace '10' with 'CUST' in customer IDs


In [107]:
Replace_ids = np.char.replace(Customer_id_str,'10','CUST')
print(Replace_ids)

['CUST1' 'CUST2' 'CUST3' 'CUST4' 'CUST5' 'CUST6' 'CUST7' 'CUST8' 'CUST9'
 '1CUST']


In [ ]:
### Question 14: Date and Time Operations

**Q14.1:** Convert years active to months


In [108]:
months = banking_data[:,4]*12
print(months)

[36 60 12 48 24 72 24 12 96 36]


In [ ]:
**Q14.2:** Calculate the average years active


In [109]:
average = np.mean(banking_data[:,4])
print(f"Average Years Active:{average:.1f}")

Average Years Active:3.5


In [ ]:
**Q14.3:** Find customers who have been active for more than 5 years


In [111]:
active_morethan_5 = banking_data[banking_data[:,4]>5]
print(f"Active Morethan 5:{active_morethan_5}")

Active Morethan 5:[[  106 16000   845    89     6]
 [  109 22000   890   103     8]]


In [ ]:
**Q14.4:** Calculate the total time all customers have been active (in years)


In [112]:
total_time = np.sum(banking_data[:,4])
print(f"Total Time:{total_time} years")

Total Time:35 years


In [ ]:
**Q14.5:** Find the customer with the shortest time active


In [115]:
Shortest_time_idx = np.argmin(banking_data[:,4])
Shortest_time_Cust = banking_data[Shortest_time_idx]
print(f"Index:{Shortest_time_Cust[0]},Years:{Shortest_time_Cust[4]}")

Index:103,Years:1


In [ ]:
### Question 15: Advanced Array Operations

**Q15.1:** Apply a function to calculate 5% interest on all account balances


In [116]:
New_balance = banking_data[:,1]*1.05
print(New_balance)

[ 5250. 12600.  2625.  8190.  3150. 16800.  4200.  1029. 23100.   525.]


In [ ]:
**Q15.2:** Use `np.where` to categorize customers by balance ranges


In [118]:
x = np.where(banking_data[:,1]>1000 ,"high","low")
print(x)

['high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'high' 'low']


In [ ]:
**Q15.3:** Use `np.select` to categorize customers by credit score ranges


In [124]:
conditions = [banking_data[:,2]<350,
              (banking_data[:,2]>=350) & (banking_data[:,2]<650),
              banking_data[:,2]>=650]
choices = ['Low','Medium','High']
categories = np.select(conditions,choices,default='unknown')
print(categories)

['High' 'High' 'Medium' 'High' 'Medium' 'High' 'High' 'Medium' 'High'
 'Medium']


In [ ]:
**Q15.4:** Use `np.piecewise` to apply different interest rates based on balance


In [133]:

def low_int(x): return x * 1.03
def mid_int(x): return x * 1.06 
def high_int(x): return x * 1.09

New_balances = np.piecewise(banking_data[:,1],
                            [banking_data[:,1]<4000,(banking_data[:,1]>=4000) & (banking_data[:,1]<8050),banking_data[:,1]>=8050],
                             [low_int,mid_int,high_int])
print(New_balances)

[ 5300 13080  2575  8268  3090 17440  4240  1009 23980   515]


In [ ]:
**Q15.5:** Use `np.apply_along_axis` to calculate the sum of each row


In [134]:
row_sums = np.apply_along_axis(np.sum,1,banking_data)
print(row_sums)

[ 5869 12839  3226  8765  3665 17046  4844  1711 23110  1048]


In [1]:
import numpy as np
import pandas as pd
# Banking data: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [101, 5000, 720, 45, 3],
    [102, 12000, 680, 52, 5],
    [103, 2500, 610, 12, 1],
    [104, 7800, 790, 67, 4],
    [105, 3000, 550, 8, 2],
    [106, 16000, 845, 89, 6],
    [107, 4000, 700, 35, 2],
    [108, 980, 600, 22, 1],
    [109, 22000, 890, 103, 8],
    [110, 500, 430, 5, 3]
])

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")



ORIGINAL BANKING DATA:
[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]

Data shape: (10, 5)
Data type: int64


In [ ]:
### Question 16: Array Concatenation and Stacking

**Q16.1:** Concatenate two arrays horizontally using `np.hstack()`


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hor_stack = np.hstack([arr1, arr2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Horizontal stack: {hor_stack}")


Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontal stack: [1 2 3 4 5 6]


In [ ]:
**Q16.2:** Concatenate two arrays vertically using `np.vstack()`


In [6]:

ver_stack = np.vstack([arr1, arr2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Vertical stack:\n {ver_stack}")


Array 1: [1 2 3]
Array 2: [4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]


In [ ]:
**Q16.3:** Concatenate arrays along a specific axis using `np.concatenate()`


In [9]:
concatenate = np.concatenate([arr1, arr2], axis=0)
print(f"Concatenated along axis 0: {concatenate}")

Concatenated along axis 0: [1 2 3 4 5 6]


In [ ]:
**Q16.4:** Stack arrays depth-wise using `np.dstack()`


In [13]:
depthstack = np.dstack([arr1,arr2])
print(f"Depth Wise Stack:{depthstack}")

Depth Wise Stack:[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
**Q16.5:** Create a column stack using `np.column_stack()`


In [14]:
c_stack = np.column_stack([arr1,arr2])
print(f"Column Stack:{c_stack}")

Column Stack:[[1 4]
 [2 5]
 [3 6]]


In [ ]:
### Question 17: Array Splitting Operations

**Q17.1:** Split an array into 3 equal parts using `np.split()`


In [15]:
arr_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
split_parts = np.split(arr_to_split, 3)
print(f"Original array: {arr_to_split}")
for i, part in enumerate(split_parts):
    print(f"Part {i+1}: {part}")


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Part 1: [1 2 3 4]
Part 2: [5 6 7 8]
Part 3: [ 9 10 11 12]


In [ ]:
**Q17.2:** Split an array at specific indices using `np.split()`


In [16]:
arr_split = np.array([1,2,3,4,5,6,7,8,9])
split_indices = np.split(arr_split,[4,7])
print(f"Original Array:{arr_split}")
for i,part in enumerate(split_indices):
    print(f"Part {i+1}:{part}")

Original Array:[1 2 3 4 5 6 7 8 9]
Part 1:[1 2 3 4]
Part 2:[5 6 7]
Part 3:[8 9]


In [ ]:
**Q17.3:** Split an array horizontally using `np.hsplit()`


In [20]:
arr2d = np.array([[1,2,3],[4,5,6]])
array_split = np.hsplit(arr2d,3)
print(f"Original array:{arr2d}")
for i,part in enumerate(array_split):
    print(f" Horizantal Part {i+1}:{part}")

Original array:[[1 2 3]
 [4 5 6]]
 Horizantal Part 1:[[1]
 [4]]
 Horizantal Part 2:[[2]
 [5]]
 Horizantal Part 3:[[3]
 [6]]


In [ ]:
**Q17.4:** Split an array vertically using `np.vsplit()`


In [23]:
arr2d = np.array([[1,2,3],[4,5,6]])
array_split = np.vsplit(arr2d,2)
print(f"Original array:{arr2d}")
for i,part in enumerate(array_split):
    print(f" Vertical Part {i+1}:{part}")

Original array:[[1 2 3]
 [4 5 6]]
 Vertical Part 1:[[1 2 3]]
 Vertical Part 2:[[4 5 6]]


In [ ]:
**Q17.5:** Split an array into equal chunks using `np.array_split()`


In [26]:
chunks = np.array_split(arr_split,5)
print(f"Chunks into 5 parts:")
for i,chunk in enumerate(chunks):
    print(f"Chunk {i+1}:{chunk}")

Chunks into 5 parts:
Chunk 1:[1 2]
Chunk 2:[3 4]
Chunk 3:[5 6]
Chunk 4:[7 8]
Chunk 5:[9]


In [ ]:
### Question 18: Array Repetition and Tiling

**Q18.1:** Repeat each element of an array 3 times using `np.repeat()`


In [27]:
Repeat = np.repeat(arr1,3)
print(f"Original Array:{arr1}")
print(f"Repeats:{Repeat}")

Original Array:[1 2 3]
Repeats:[1 1 1 2 2 2 3 3 3]


In [ ]:
**Q18.2:** Repeat an entire array 2 times using `np.tile()`


In [28]:
tile = np.tile(arr2,2)
print(f"Original Array:{arr2}")
print(f"Tile:{tile}")

Original Array:[4 5 6]
Tile:[4 5 6 4 5 6]


In [ ]:
**Q18.3:** Repeat a 2D array using `np.tile()`


In [29]:
ar = np.array([[5,6],[7,8]])
tile = np.tile(ar,(4,4))
print(f"Original array:{ar}")
print(f"Tile:{tile}")

Original array:[[5 6]
 [7 8]]
Tile:[[5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]
 [5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]
 [5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]
 [5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]]


In [ ]:
**Q18.4:** Create a pattern using `np.tile()`


In [31]:
pattern = np.array([1,2,3,4])
tile = np.tile(pattern,6)
print(f"original array:{pattern}")
print(f"Tile:{tile}")

original array:[1 2 3 4]
Tile:[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]


In [ ]:
**Q18.5:** Repeat elements with different counts using `np.repeat()`


In [32]:
array = np.array([4,5,6])
repeat_counts = [2,3,5]
repeat_var = np.repeat(array,repeat_counts)
print(f"original array:{array}")
print(f"Repeat count:{repeat_counts}")
print(f"Repeat Var:{repeat_var}")


original array:[4 5 6]
Repeat count:[2, 3, 5]
Repeat Var:[4 4 5 5 5 6 6 6 6 6]


In [ ]:
### Question 19: Array Comparison and Logical Operations

**Q19.1:** Compare two arrays for equality using `np.array_equal()`


In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(f"arr a:{a}")
print(f"arr b:{b}")
print(f"arr c:{c}")
print(f"Array a equals b:{np.array_equal(a,b)}")
print(f"Array b equals c:{np.array_equal(b,c)}")

arr a:[1 2 3]
arr b:[4 5 6]
arr c:[7 8 9]
Array a equals b:False
Array b equals c:False


In [ ]:
**Q19.2:** Check if arrays are close using `np.allclose()`


In [ ]:
**Q19.3:** Apply logical AND operation between arrays


In [37]:
logical_and = np.logical_and(a > 1, a < 3)
print(f"Array: {b}")
print(f"Logical AND (1 < x < 3): {logical_and}")

Array: [4 5 6]
Logical AND (1 < x < 3): [False  True False]


In [ ]:
**Q19.4:** Apply logical OR operation between arrays


In [ ]:
**Q19.5:** Apply logical NOT operation to an array


In [ ]:
### Question 20: Array Set Operations

**Q20.1:** Find unique elements in an array using `np.unique()`


In [38]:
duplicate_array = np.array([2,2,3,3,4,5,6,6,6,])
unique = np.unique(duplicate_array)
print(f"Duplicate Array:{duplicate_array}")
print(f"Unique:{unique}")

Duplicate Array:[2 2 3 3 4 5 6 6 6]
Unique:[2 3 4 5 6]


In [ ]:
**Q20.2:** Find the intersection of two arrays using `np.intersect1d()`


In [40]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([4,5,6])
intersection = np.intersect1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Intersection:{intersection}")

A1:[1 2 3 4 5]
A2:[4 5 6]
Intersection:[4 5]


In [ ]:
**Q20.3:** Find the union of two arrays using `np.union1d()`


In [41]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
union = np.union1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Union:{union}")

A1:[1 2 3]
A2:[4 5 6]
Union:[1 2 3 4 5 6]


In [ ]:
**Q20.4:** Find elements in first array but not in second using `np.setdiff1d()`


In [42]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([4,5,6])
setdiff = np.setdiff1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Setdiff:{setdiff}")

A1:[1 2 3 4 5]
A2:[4 5 6]
Setdiff:[1 2 3]


In [ ]:
**Q20.5:** Find the symmetric difference between two arrays using `np.setxor1d()`


In [44]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([4,5,6])
symmetric_diff = np.setxor1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Symmetric Diff:{symmetric_diff}")

A1:[1 2 3 4 5]
A2:[4 5 6]
Symmetric Diff:[1 2 3 6]
