In [1]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


# Retail Data – Business Questions (for `retail_data`)

**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?


In [ ]:
1. What is the **total revenue** generated across all stores?


In [2]:
a = retail_data[:,1].sum()
b = retail_data[:,3].sum()
c = a*b
print(c)

4790500000


In [ ]:
2. Which store recorded the **highest sales**?


In [3]:
retail_data[:,1].argmax()+1

np.int64(9)

In [ ]:
3. Which store recorded the **lowest sales**?


In [4]:
retail_data[:,1].argmin()+1

np.int64(1)

In [ ]:
4. What is the **average daily sales** per store?


In [5]:
retail_data[:,1].mean()

np.float64(33500.0)

In [ ]:
5. How many stores achieved sales **above ₹35,000**?


In [6]:
a = retail_data[:,1]
b = a [a > 35000]
print(b)


[41000 39000 45000]


In [ ]:
6. Which store had the **highest customer footfall**?


In [7]:
retail_data[:,2].argmax()+1

np.int64(9)

In [ ]:
7. What is the **average number of customers** per store?


In [8]:
a = retail_data[:,2].mean()
print(a)

425.0


In [ ]:
8. How many stores have **more than 450 customers**?


In [9]:
a = retail_data[:,2]
b = a[a>450]
print(b)

[500 480 550]


In [ ]:
9. Which store has the **lowest customer count**?


In [10]:
a = retail_data[:,2].argmin()+1
print(a)

1


In [ ]:
10. Is there any store where **high sales do not correspond to high customers**?


In [ ]:
11. What is the **total inventory** across all stores?


In [11]:
retail_data[:,3].sum()

np.int64(14300)

In [ ]:
12. Which store has the **highest inventory stock**?


In [12]:
retail_data[:,3].argmax()+1

np.int64(9)

In [ ]:
13. How many stores have **inventory less than 1300 units**?


In [13]:
a = retail_data[:,3]
b = a[a<1300]
print(b)

[1200 1100 1250]


In [ ]:
14. Which store has the **highest return rate** (returns ÷ inventory)?


In [14]:
a = (retail_data[:,4])/(retail_data[:,3])
a.argmax()+1

np.int64(9)

In [ ]:
15. Which stores have **returns greater than 15 units**?


In [15]:
a = retail_data[(retail_data[:,4])>15,0]
a

array([4, 7, 9])

In [ ]:
16. Is there a **positive correlation** between sales and customers?


In [ ]:
17. Which store has **high customer visits but low sales**?


In [19]:
customers = retail_data[:,2].mean()
sales = retail_data[:,1].mean()
store = retail_data[(retail_data[:,2]>customers) & (retail_data[:,1]<sales)]
store

array([[    2, 32000,   450,  1500,    15]])

In [ ]:
18. Which store has **low customers but high sales**?


In [20]:
customers = retail_data[:,2].mean()
sales = retail_data[:,1].mean()
store = retail_data[(retail_data[:,2]<customers) & (retail_data[:,1]>sales)]
store

array([[    5, 35000,   420,  1400,    12]])

In [ ]:
19. How many stores have **sales per customer above ₹90**?


In [21]:
spc = retail_data[:,1]/ retail_data[:,2]
store = np.sum(spc>90)
store

np.int64(0)

In [ ]:
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?


In [ ]:
21. If profit margin is **20% of sales**, what is the **profit per store**?


In [22]:
profit = 0.2 * retail_data[:,1]
profit

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [ ]:
22. Which store has the **highest profit**?


In [23]:
profit = 0.2 * retail_data[:,1]
profit.argmax()+1

np.int64(9)

In [ ]:
23. Which store has the **lowest profit**?


In [24]:
profit = 0.2 * retail_data[:,1]
profit.argmin()+1

np.int64(1)

In [ ]:
24. If sales increase by **10% next month**, what are the **new sales figures**?


In [25]:
sales = 0.1*retail_data[:,1] 
sales

array([2500., 3200., 2800., 4100., 3500., 2700., 3900., 3000., 4500.,
       3300.])

In [ ]:
25. How will **total profit** change with the 10% sales increase?


In [26]:
sales = 0.1*retail_data[:,1] + retail_data[:,1]
sales

array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [ ]:
26. Which stores need **inventory restocking** based on sales and current stock?


In [27]:
sal = retail_data[:,1].mean()
ret = retail_data[:,4].mean()
res = retail_data[(retail_data[:,1] > sal) & (retail_data[:,4] < ret)]
res

array([[    5, 35000,   420,  1400,    12]])

In [ ]:
27. Which stores show **high returns percentage** and might require **quality checks**?


In [ ]:
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?


In [ ]:
29. Which store is the **worst performer overall**?


In [ ]:
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
